name: Blog
description: Yup
meta_description: "Blog - yup"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: '/'
domain_name: 'https://blog.lholmquist.org'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog.lholmquist.org'
author:         'Lucas Holmquist'
bio: This is my Bio. I Know. Interesting Stuff
